version: "2"
services:
  # MySQL database shared with tomcat containers.
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sessions
      MYSQL_USER: javauser
      MYSQL_PASSWORD: javapass
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
      - "./dump:/var/lib/mysql-files/"
    ports:
      - 3306


  # Tomcat server.
  tomcat:
    image: tomcat:latest
    container_name: tomcat
    volumes:
      - "./target:/usr/local/tomcat/webapps/"
    ports:
      - 8080:8080
    links:
      - db
